const resObj = {
  data: [
    {
      id: "25958975",
      name: "The Chicken Co",
      type: "selection_intel_store",
      address: "5732 N Springboro Pike, Dayton, OH 45449",
      rating: 4.5,
      imageUrl: "https://example.com/hotel1.jpg",
    },
    {
      id: "11422594",
      name: "Chicken Krikets",
      type: "selection_intel_store",
      address: "2301 Germantown St, Dayton, OH 45417",
      rating: 4.2,
      imageUrl: "https://example.com/hotel2.jpg",
    },
    {
      id: "10835463",
      name: "Raising Cane'S Chicken Fingers",
      type: "selection_intel_store",
      address: "4384 Indian Ripple Rd, Dayton, OH 45440",
      rating: 4.8,
      imageUrl: "https://example.com/hotel3.jpg",
    },
    {
      id: "15473683",
      name: "Krispy Krunchy Chicken",
      type: "selection_intel_store",
      address: "3800 Colonel Glenn Hwy, Beavercreek, OH 45324",
      rating: 4.6,
      imageUrl: "https://example.com/hotel4.jpg",
    },
    {
      id: "13078577",
      name: "Degs Flame Grilled Chicken",
      type: "selection_intel_store",
      address: "15 Greene Blvd, Dayton, OH 45440",
      rating: 4.3,
      imageUrl: "https://example.com/hotel5.jpg",
    },
    {
      id: "12654554",
      name: "Halal Homestyle Chili And Bourbon Chicken",
      type: "selection_intel_store",
      address: "131 N Ludlow St, Dayton, OH 45402",
      rating: 4.1,
      imageUrl: "https://example.com/hotel6.jpg",
    },
    {
      id: "14647140",
      name: "Carillon Brewing",
      type: "selection_intel_store",
      address: "1000 Carillon Blvd, Dayton, OH 45409",
      rating: 4.7,
      imageUrl: "https://example.com/hotel7.jpg",
    },
    {
      id: "14121114",
      name: "Rahns Artisan Breads",
      type: "selection_intel_store",
      address: "215 Kiser St, Dayton, OH 45404",
      rating: 4.4,
      imageUrl: "https://example.com/hotel8.jpg",
    },
    {
      id: "18160938",
      name: "Einstein Bros. Bagels",
      type: "selection_intel_store",
      address: "2950 Hobson Way, Fairborn, OH 45324",
      rating: 4.5,
      imageUrl: "https://example.com/hotel9.jpg",
    },
    {
      id: "11780549",
      name: "Hickory Barb Que",
      type: "selection_intel_store",
      address: "1082 Brown St, Dayton, OH 45409",
      rating: 4.2,
      imageUrl: "https://example.com/hotel10.jpg",
    },
    {
      id: "19248576",
      name: "Urban Grille",
      type: "selection_intel_store",
      address: "1200 Brown St, Dayton, OH 45409",
      rating: 4.3,
      imageUrl: "https://example.com/hotel11.jpg",
    },
    {
      id: "20398475",
      name: "Taco Haven",
      type: "selection_intel_store",
      address: "3000 Far Hills Ave, Kettering, OH 45429",
      rating: 4.5,
      imageUrl: "https://example.com/hotel12.jpg",
    },
    {
      id: "21437489",
      name: "Bella Italia",
      type: "selection_intel_store",
      address: "4000 Indian Ripple Rd, Dayton, OH 45440",
      rating: 4.7,
      imageUrl: "https://example.com/hotel13.jpg",
    },
    {
      id: "22457845",
      name: "Sushi Star",
      type: "selection_intel_store",
      address: "5000 N Main St, Dayton, OH 45415",
      rating: 4.6,
      imageUrl: "https://example.com/hotel14.jpg",
    },
    {
      id: "23569847",
      name: "Pizza Palace",
      type: "selection_intel_store",
      address: "6000 Wilmington Pike, Dayton, OH 45459",
      rating: 4.2,
      imageUrl: "https://example.com/hotel15.jpg",
    },
    {
      id: "24698574",
      name: "Burger Barn",
      type: "selection_intel_store",
      address: "7000 S Dixie Dr, Dayton, OH 45439",
      rating: 4.4,
      imageUrl: "https://example.com/hotel16.jpg",
    },
    {
      id: "25789465",
      name: "Steak House",
      type: "selection_intel_store",
      address: "8000 Miller Ln, Dayton, OH 45414",
      rating: 4.5,
      imageUrl: "https://example.com/hotel17.jpg",
    },
    {
      id: "26854789",
      name: "Vegan Delight",
      type: "selection_intel_store",
      address: "9000 Hoke Rd, Clayton, OH 45315",
      rating: 4.6,
      imageUrl: "https://example.com/hotel18.jpg",
    },
    {
      id: "27945874",
      name: "Seafood Shack",
      type: "selection_intel_store",
      address: "10000 Salem Ave, Dayton, OH 45426",
      rating: 4.5,
      imageUrl: "https://example.com/hotel19.jpg",
    },
    {
      id: "28974568",
      name: "Dessert Haven",
      type: "selection_intel_store",
      address: "11000 W 3rd St, Dayton, OH 45427",
      rating: 4.3,
      imageUrl: "https://example.com/hotel20.jpg",
    },
    {
      id: "29487569",
      name: "Healthy Bites",
      type: "selection_intel_store",
      address: "12000 Gettysburg Ave, Dayton, OH 45417",
      rating: 4.7,
      imageUrl: "https://example.com/hotel21.jpg",
    },
    {
      id: "30547896",
      name: "Mediterranean Grill",
      type: "selection_intel_store",
      address: "13000 N Main St, Dayton, OH 45415",
      rating: 4.8,
      imageUrl: "https://example.com/hotel22.jpg",
    },
    {
      id: "31459876",
      name: "BBQ King",
      type: "selection_intel_store",
      address: "14000 S Main St, Dayton, OH 45402",
      rating: 4.9,
      imageUrl: "https://example.com/hotel23.jpg",
    },
    {
      id: "32547896",
      name: "Pasta Palace",
      type: "selection_intel_store",
      address: "15000 E 3rd St, Dayton, OH 45410",
      rating: 4.3,
      imageUrl: "https://example.com/hotel24.jpg",
    },
    {
      id: "33569847",
      name: "Sandwich Stop",
      type: "selection_intel_store",
      address: "16000 W 3rd St, Dayton, OH 45417",
      rating: 4.4,
      imageUrl: "https://example.com/hotel25.jpg",
    },
    {
      id: "34587469",
      name: "Taco Town",
      type: "selection_intel_store",
      address: "17000 Shiloh Springs Rd, Trotwood, OH 45426",
      rating: 4.2,
      imageUrl: "https://example.com/hotel26.jpg",
    },
    {
      id: "35698547",
      name: "Sushi World",
      type: "selection_intel_store",
      address: "18000 S Smithville Rd, Dayton, OH 45420",
      rating: 4.5,
      imageUrl: "https://example.com/hotel27.jpg",
    },
    {
      id: "36789458",
      name: "Burger Boss",
      type: "selection_intel_store",
      address: "19000 Wilmington Ave, Dayton, OH 45420",
      rating: 4.3,
      imageUrl: "https://example.com/hotel28.jpg",
    },
    {
      id: "37894568",
      name: "Pizza Planet",
      type: "selection_intel_store",
      address: "20000 Watervliet Ave, Dayton, OH 45420",
      rating: 4.6,
      imageUrl: "https://example.com/hotel29.jpg",
    },
    {
      id: "38965487",
      name: "Pasta House",
      type: "selection_intel_store",
      address: "21000 Indian Ripple Rd, Dayton, OH 45440",
      rating: 4.4,
      imageUrl: "https://example.com/hotel30.jpg",
    },
    {
      id: "39874568",
      name: "BBQ Joint",
      type: "selection_intel_store",
      address: "22000 Stroop Rd, Dayton, OH 45429",
      rating: 4.6,
    },
  ],
};

export default resObj;
